# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# include:
# shield: settings_reset
# control, add individual board + shield combinations to
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nrfmicro_13
    shield: swoop_left
  - board: nrfmicro_13
    shield: swoop_right
 - board: nrfmicro_13
    shield: settings_reset
